package synth

// functionWords are skipped by synonymSwap. Swapping them produces
// ungrammatical noise (e.g. "show me" -> "demonstrate me"), so we leave them
// alone. The classifier learns the surrounding structure regardless.
var functionWords = map[string]bool{
	"a": true, "an": true, "the": true,
	"of": true, "in": true, "on": true, "at": true,
	"to": true, "for": true, "from": true, "into": true,
	"and": true, "or": true, "but": true, "so": true,
	"is": true, "are": true, "was": true, "were": true,
	"be": true, "been": true, "being": true,
	"i": true, "you": true, "we": true, "they": true,
	"me": true, "my": true, "your": true, "our": true,
	"this": true, "that": true, "these": true, "those": true,
	"it": true, "its": true,
	"do": true, "does": true, "did": true,
	"have": true, "has": true, "had": true,
	"can": true, "could": true, "would": true, "should": true,
	"will": true, "shall": true,
	"as": true, "if": true, "than": true, "then": true,
	"about": true, "like": true, "just": true,
	"with": true, // only safe in some contexts; skip for safety
	"by": true, "up": true, "out": true, "off": true,
	"all": true, "any": true, "some": true, "no": true,
	"very": true, "more": true, "most": true, "much": true,
}

// synonyms is the built-in synonym map. Lower-case keys, lower-case values.
// Only content words live here — function words are filtered by synonymSwap.
var synonyms = map[string][]string{
	"make":      {"create", "generate", "build", "produce"},
	"create":    {"make", "generate", "build", "produce"},
	"generate":  {"make", "produce", "build"},
	"produce":   {"make", "create", "generate", "build"},
	"video":     {"clip", "footage", "movie", "sequence"},
	"clip":      {"video", "footage", "movie"},
	"footage":   {"video", "clip", "movie"},
	"show":      {"display", "demonstrate", "reveal", "depict"},
	"display":   {"show", "demonstrate", "reveal"},
	"short":     {"brief", "quick", "little"},
	"long":      {"extended", "lengthy"},
	"good":      {"nice", "great", "excellent", "awesome"},
	"cool":      {"awesome", "amazing", "rad", "sweet"},
	"complex":   {"elaborate", "intricate", "detailed"},
	"simple":    {"plain", "basic", "minimal"},
	"cinematic": {"filmic", "movie-like"},
	"realistic": {"photorealistic", "true-to-life", "lifelike"},
	"animated":  {"cartoon", "anime-style"},
	"want":      {"need", "would like"},
	"need":      {"require", "want"},
	"give":      {"make", "create", "produce"},
	"scene":     {"shot", "sequence"},
	"shot":      {"scene", "sequence"},
	"animation": {"cartoon", "anime"},
	"style":     {"look", "vibe", "feel"},
	"high":      {"ultra", "premium"},
	"quality":   {"resolution", "fidelity"},
	"cgi":       {"computer-generated", "CGI"},
	"motion":    {"kinetic", "movement"},
	"graphics":  {"visuals", "gfx"},
	"logo":      {"brand mark", "wordmark"},
	"reveal":    {"unveiling", "intro"},
	"intro":     {"introduction", "opening"},
	"title":     {"header", "heading"},
	"sequence":  {"scene", "sequence"},
	"epic":      {"grand", "spectacular"},
	"dramatic":  {"theatrical", "intense"},
	"stunning":  {"breathtaking", "amazing"},
	"beautiful": {"gorgeous", "lovely"},
	"funny":     {"humorous", "comedic"},
	"quick":     {"fast", "rapid"},
	"render":    {"generate", "produce"},
	"rotate":    {"spin", "revolve"},
	"spinning":  {"rotating", "turning"},
	"walking":   {"strolling", "ambling"},
	"running":   {"sprinting", "racing"},
	"flying":    {"soaring", "gliding"},
	"high-quality": {"premium", "top-quality"},
	"ultra":     {"premium", "top"},
	"premium":   {"high-end", "quality"},
	"documentary": {"doc", "factual"},
	"concert":   {"show", "performance"},
	"fashion":   {"couture", "style"},
	"explore":   {"discover", "investigate"},
	"adventure": {"journey", "quest"},
	"magical":   {"enchanted", "mystical"},
	"sweeping":  {"panoramic", "broad"},
	"historical": {"period", "classic"},
	"futuristic": {"sci-fi", "advanced"},
	"athletic":  {"sporty", "fit"},
}
